In [29]:
import pickle
import numpy as np

In [30]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl','rb'))
clf = pickle.load(open('models/clf.pkl','rb'))

In [31]:
#Assume user input
#Pclass/gender/age/sibsp/parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 's'], dtype=object).reshape(1, 7)


In [32]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 's']], dtype=object)

In [33]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\KIIT\anaconda3\anaconda\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [34]:
test_input_sex

array([[0., 1.]])

In [35]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [36]:
test_input_embarked

array([[0., 0., 0.]])

In [37]:
test_input_age = test_input[:,2].reshape(1,1)

In [38]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [39]:
test_input_transformed.shape

(1, 10)

In [41]:

arr = np.array([1], dtype=np.int64)
